"""Modal deploy target.

Emits a ``modal_app.py`` that wraps the Quay app under a Modal ``@asgi_app``
function. ``modal deploy modal_app.py`` then ships it.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any, ClassVar

_MODAL_APP = '''\
"""Generated by quay-deploy-modal."""

import modal

image = modal.Image.debian_slim().pip_install("quay", "uvicorn[standard]")

app = modal.App("{name}", image=image)


@app.function()
@modal.asgi_app()
def fastapi_app():
    from app.app import app as quay_app

    return quay_app
'''


class ModalDeploy:
    contract_version: ClassVar[str] = "v1.0"

    def __init__(self, *, app_name: str = "quay-app") -> None:
        self.app_name = app_name

    async def startup(self, settings: Any) -> None: ...
    async def shutdown(self) -> None: ...
    async def ready(self) -> bool:
        return True

    def manifest(self) -> dict[str, Any]:
        return {"target": "modal", "app": self.app_name, "files": ["modal_app.py"]}

    def package(self, *, target_dir: str | Path = ".") -> bytes:
        target = Path(target_dir)
        target.mkdir(parents=True, exist_ok=True)
        body = _MODAL_APP.format(name=self.app_name)
        (target / "modal_app.py").write_text(body)
        return body.encode()

    async def push(self, target: str) -> str:
        del target
        if shutil.which("modal") is None:
            msg = "modal not on PATH — install Modal's CLI to deploy."
            raise RuntimeError(msg)
        result = subprocess.run(
            ["modal", "deploy", "modal_app.py"],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"modal deploy failed: {result.stderr}")
        return result.stdout


def plugin(settings: Any) -> None:
    from quay import register

    name = getattr(settings, "modal_app", None) or "quay-app"
    register(ModalDeploy(app_name=str(name)))


__all__ = ["ModalDeploy", "plugin"]
