"""Docker deploy target for :class:`quay.contracts.DeployTarget`.

Emits a multi-stage ``Dockerfile`` plus a ``compose.yaml`` that wires
Postgres + Redis for prod-like local runs. ``push()`` is a no-op — Docker
images are pushed by the registry CLI, not this adapter.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, ClassVar

_DOCKERFILE = """\
# Generated by quay-deploy-docker.
FROM python:3.13-slim AS builder
WORKDIR /app
RUN pip install --no-cache-dir uv
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen --no-dev || uv sync

FROM python:3.13-slim
WORKDIR /app
COPY --from=builder /app/.venv /app/.venv
COPY . .
ENV PATH=/app/.venv/bin:$PATH
EXPOSE 8000
CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]
"""

_COMPOSE = """\
services:
  app:
    build: .
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgresql+asyncpg://quay:quay@db/quay
      REDIS_URL: redis://cache:6379
    depends_on: [db, cache]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: quay
      POSTGRES_PASSWORD: quay
      POSTGRES_DB: quay
    volumes: ["pgdata:/var/lib/postgresql/data"]
  cache:
    image: redis:7-alpine

volumes:
  pgdata:
"""


class DockerDeploy:
    contract_version: ClassVar[str] = "v1.0"

    async def startup(self, settings: Any) -> None: ...
    async def shutdown(self) -> None: ...
    async def ready(self) -> bool:
        return True

    def manifest(self) -> dict[str, Any]:
        return {"target": "docker", "files": ["Dockerfile", "compose.yaml"]}

    def package(self, *, target_dir: str | Path = ".") -> bytes:
        """Write ``Dockerfile`` and ``compose.yaml`` into ``target_dir``.

        Returns the Dockerfile contents as bytes — the contract expects bytes
        and most callers want the file already on disk.
        """
        target = Path(target_dir)
        target.mkdir(parents=True, exist_ok=True)
        (target / "Dockerfile").write_text(_DOCKERFILE)
        (target / "compose.yaml").write_text(_COMPOSE)
        return _DOCKERFILE.encode()

    async def push(self, target: str) -> str:
        del target
        msg = (
            "DockerDeploy doesn't push to a registry — run `docker push` "
            "from your CI after building the image."
        )
        raise NotImplementedError(msg)


def plugin(settings: Any) -> None:
    del settings
    from quay import register

    register(DockerDeploy())


__all__ = ["DockerDeploy", "plugin"]
