from __future__ import annotations

from pathlib import Path

import pytest

import causeway.plugins as plugin_registry
from causeway_deploy_docker import DockerDeploy, plugin


@pytest.fixture(autouse=True)
def _clear_registry() -> None:
    plugin_registry.clear()


async def test_lifecycle_is_a_no_op() -> None:
    target = DockerDeploy()
    await target.startup(None)
    await target.shutdown()
    assert await target.ready() is True


def test_manifest_lists_emitted_files() -> None:
    manifest = DockerDeploy().manifest()
    assert manifest["target"] == "docker"
    assert "Dockerfile" in manifest["files"]
    assert "compose.yaml" in manifest["files"]


def test_package_writes_dockerfile_and_compose(tmp_path: Path) -> None:
    target = DockerDeploy()
    body = target.package(target_dir=tmp_path)

    dockerfile = (tmp_path / "Dockerfile").read_text()
    compose = (tmp_path / "compose.yaml").read_text()

    assert dockerfile.startswith("# Generated by causeway-deploy-docker.")
    assert "FROM python:3.13-slim" in dockerfile
    assert "EXPOSE 8000" in dockerfile
    assert body == dockerfile.encode()

    assert "services:" in compose
    assert "postgres" in compose
    assert "redis" in compose


def test_package_creates_target_dir(tmp_path: Path) -> None:
    target = DockerDeploy()
    nested = tmp_path / "nested" / "deploy"
    target.package(target_dir=nested)
    assert (nested / "Dockerfile").is_file()


async def test_push_raises_not_implemented() -> None:
    target = DockerDeploy()
    with pytest.raises(NotImplementedError, match="docker push"):
        await target.push("registry.example.com/x:latest")


def test_plugin_registers_instance() -> None:
    plugin(None)
    assert len(plugin_registry.registered()) == 1
    assert isinstance(plugin_registry.registered()[0], DockerDeploy)
