"""Fly.io deploy target — emits ``fly.toml`` + Dockerfile, calls ``flyctl``."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any, ClassVar

_FLY_TOML = """\
# Generated by quay-deploy-fly.
app = "{name}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 8000
  protocol = "tcp"
"""


class FlyDeploy:
    contract_version: ClassVar[str] = "v1.0"

    def __init__(self, *, app_name: str = "quay-app") -> None:
        self.app_name = app_name

    async def startup(self, settings: Any) -> None: ...
    async def shutdown(self) -> None: ...
    async def ready(self) -> bool:
        return True

    def manifest(self) -> dict[str, Any]:
        return {
            "target": "fly",
            "app": self.app_name,
            "files": ["fly.toml", "Dockerfile"],
        }

    def package(self, *, target_dir: str | Path = ".") -> bytes:
        target = Path(target_dir)
        target.mkdir(parents=True, exist_ok=True)
        body = _FLY_TOML.format(name=self.app_name)
        (target / "fly.toml").write_text(body)
        # Reuse the docker plugin's Dockerfile if it's installed, else inline.
        try:
            from quay_deploy_docker import DockerDeploy

            DockerDeploy().package(target_dir=target)
        except ImportError:
            (target / "Dockerfile").write_text(
                "FROM python:3.13-slim\nWORKDIR /app\nCOPY . .\n"
                'CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]\n',
            )
        return body.encode()

    async def push(self, target: str) -> str:
        del target
        if shutil.which("flyctl") is None:
            msg = "flyctl not on PATH — install Fly's CLI to push."
            raise RuntimeError(msg)
        result = subprocess.run(
            ["flyctl", "deploy", "--app", self.app_name],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"flyctl deploy failed: {result.stderr}")
        return result.stdout


def plugin(settings: Any) -> None:
    from quay import register

    name = getattr(settings, "fly_app", None) or "quay-app"
    register(FlyDeploy(app_name=str(name)))


__all__ = ["FlyDeploy", "plugin"]
